# Generated by Django 5.0.7 on 2025-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_seed_baskets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklybasketitem',
            name='week_of',
            field=models.DateField(blank=True, null=True),
        ),
    ]
