# Generated by Django 5.0.7 on 2025-01-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_alter_weeklybasketitem_week_of'),
        ('products', '0005_alter_productbasicfood_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'basket'},
        ),
        migrations.AlterModelOptions(
            name='basketbasicfood',
            options={'verbose_name': 'basket basic food'},
        ),
        migrations.AlterModelOptions(
            name='basketprice',
            options={'verbose_name': 'basket price'},
        ),
        migrations.AlterModelOptions(
            name='weeklybasketitem',
            options={'verbose_name': 'weekly basket item'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='basketbasicfood',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_foods', to='baskets.basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='basketbasicfood',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='basketprice',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='baskets.basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='basketprice',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='weeklybasketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_items', to='baskets.basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='weeklybasketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='weeklybasketitem',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='weeklybasketitem',
            name='week_of',
            field=models.DateField(blank=True, null=True, verbose_name='week of'),
        ),
    ]
