# Generated by Django 5.0.7 on 2025-01-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_alter_basket_options_alter_basketbasicfood_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketprice',
            options={'verbose_name': 'basket price', 'verbose_name_plural': 'basket prices'},
        ),
    ]
