# Generated by Django 5.0.7 on 2025-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_define_task_permission_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntask',
            name='user_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='min_req_volunteers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
