# Generated by Django 5.0.7 on 2025-01-22 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_assigntask_user_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigntask',
            options={'verbose_name': 'assign task'},
        ),
        migrations.AlterModelOptions(
            name='publishtask',
            options={'verbose_name': 'publish task'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task'},
        ),
        migrations.AlterModelOptions(
            name='tasktimeslot',
            options={'verbose_name': 'task time slot'},
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='assigned_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='assigned at'),
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='task_and_time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktimeslot', verbose_name='task time slot'),
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='assigntask',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='volunteer'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='published_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_tasks', to='tasks.task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='publishtask',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published at'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='operation_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='operation order'),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, null=True, verbose_name='jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='min_req_volunteers',
            field=models.IntegerField(blank=True, null=True, verbose_name='minimum required volunteers'),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tasks.task', verbose_name='task'),
        ),
        migrations.AlterField(
            model_name='tasktimeslot',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='time start'),
        ),
    ]
