# Generated by Django 5.0.7 on 2025-01-20 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baskets', '0003_alter_weeklybasketitem_week_of'),
        ('tasks', '0004_assigntask_user_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_for_week_of', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_budget', models.FloatField(default=0.0)),
                ('total_purchase_cost', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorOrderBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket_name', models.CharField(blank=True, max_length=255, null=True)),
                ('basket_quantity', models.PositiveIntegerField(default=0)),
                ('total_basket_budget', models.FloatField(default=0.0)),
                ('basket_cost', models.FloatField(default=0.0)),
                ('distributor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to='orders.distributororder')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorOrderBasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_price', models.FloatField(default=0.0)),
                ('units_per_basket', models.FloatField(default=0.0)),
                ('cost_per_basket', models.FloatField(default=0.0)),
                ('distributor_order_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_order_items', to='orders.distributororderbasket')),
                ('weekly_basket_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_order_items', to='baskets.weeklybasketitem')),
            ],
        ),
        migrations.CreateModel(
            name='MemberOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.FloatField(default=0.0)),
                ('reference_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_reference_task', to='tasks.publishtask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='distributororder',
            name='member_orders',
            field=models.ManyToManyField(related_name='distributor_orders', to='orders.memberorder'),
        ),
        migrations.CreateModel(
            name='MemberSelectedBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(blank=True, null=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baskets.basket')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='orders.memberorder')),
            ],
        ),
    ]
