# Generated by Django 5.0.7 on 2025-01-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0004_alter_basket_options_alter_basketbasicfood_options_and_more'),
        ('orders', '0001_initial'),
        ('tasks', '0005_alter_assigntask_options_alter_publishtask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distributororder',
            options={'verbose_name': 'distributor order'},
        ),
        migrations.AlterModelOptions(
            name='distributororderbasket',
            options={'verbose_name': 'distributor order basket'},
        ),
        migrations.AlterModelOptions(
            name='distributororderbasketitem',
            options={'verbose_name': 'distributor order basket item'},
        ),
        migrations.AlterModelOptions(
            name='memberorder',
            options={'verbose_name': 'member order'},
        ),
        migrations.AlterModelOptions(
            name='memberselectedbasket',
            options={'verbose_name': 'member selected basket'},
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='member_orders',
            field=models.ManyToManyField(related_name='distributor_orders', to='orders.memberorder', verbose_name='member orders'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='order_for_week_of',
            field=models.DateField(blank=True, null=True, verbose_name='order for week of'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='total_budget',
            field=models.FloatField(default=0.0, verbose_name='Total budget'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='total_orders',
            field=models.PositiveIntegerField(default=0, verbose_name='total orders'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='total_purchase_cost',
            field=models.FloatField(default=0.0, verbose_name='total purchase cost'),
        ),
        migrations.AlterField(
            model_name='distributororder',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='distributororderbasket',
            name='basket_cost',
            field=models.FloatField(default=0.0, verbose_name='basket cost'),
        ),
        migrations.AlterField(
            model_name='distributororderbasket',
            name='basket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='basket name'),
        ),
        migrations.AlterField(
            model_name='distributororderbasket',
            name='basket_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='basket quantity'),
        ),
        migrations.AlterField(
            model_name='distributororderbasket',
            name='distributor_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_orders', to='orders.distributororder', verbose_name='distributor order'),
        ),
        migrations.AlterField(
            model_name='distributororderbasket',
            name='total_basket_budget',
            field=models.FloatField(default=0.0, verbose_name='Total basket budget'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='cost_per_basket',
            field=models.FloatField(default=0.0, verbose_name='cost per basket'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='distributor_order_basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_order_items', to='orders.distributororderbasket', verbose_name='distributor order basket item'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='quantity_price',
            field=models.FloatField(default=0.0, verbose_name='quantity price'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='units_per_basket',
            field=models.FloatField(default=0.0, verbose_name='units per basket'),
        ),
        migrations.AlterField(
            model_name='distributororderbasketitem',
            name='weekly_basket_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_order_items', to='baskets.weeklybasketitem', verbose_name='weekly basket item'),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='reference_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_reference_task', to='tasks.publishtask', verbose_name='reference task'),
        ),
        migrations.AlterField(
            model_name='memberorder',
            name='total_cost',
            field=models.FloatField(default=0.0, verbose_name='total cost'),
        ),
        migrations.AlterField(
            model_name='memberselectedbasket',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baskets.basket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='memberselectedbasket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='orders.memberorder', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='memberselectedbasket',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='memberselectedbasket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
