# Generated by Django 5.0.7 on 2025-01-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_import_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='organic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='productbasicfood',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_foods', to='products.product'),
        ),
    ]
